import { AppProvider } from "./Context";
import "./globals.css";

export const metadata = {
  title: "Deutsch",
  description: "Generated by create RAMIN MAGHSOUDI",
};

export default async function RootLayout({ children }) {
  return (
    <AppProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </AppProvider>
  );
}
