import Add from "@/components/add/Add";
import "./globals.css";
import Wrapper from "@/components/wrapper/Wrapper";
import { AppProvider } from "./Context";
import { FetchAll } from "@/actions";
import Bodi from "@/components/bodi/Bodi";

export const metadata = {
  title: "Deutsch",
  description: "Generated by create RAMIN MAGHSOUDI",
};

export default async function RootLayout({ children }) {
  const fetchAll = await FetchAll("Laibrary");
  const grouped = Object.values(
    (fetchAll || []).reduce((acc, item) => {
      const key = item.Title?.trim().toLowerCase() || "";
      if (!acc[key]) {
        acc[key] = {
          Title: item.Title,
          EN: item.EN,
          FA: item.FA,
          ID: item.id,
          items: [],
          tables: [],
        };
      }
      acc[key].items.push(item);
      return acc;
    }, {}),
  );
  const groupedTD = Object.values(
    (fetchAll || []).reduce((acc, item) => {
      const key = item.Title?.trim().toLowerCase() || "";
      if (!acc[key]) {
        acc[key] = {
          tables: [],
        };
      }
      if (item.Type !== null && item.Type.split("-")[0] === "TD") {
        acc[key].tables.push(item);
      }
      return acc;
    }, {}),
  );
  // HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
  // const grouped = Object.values(
  //   (fetchAll || []).reduce((acc, item) => {
  //     const key = item.Title?.trim().toLowerCase() || "";
  //     if (!acc[key]) {
  //       acc[key] = {
  //         Title: item.Title,
  //         EN: item.EN,
  //         FA: item.FA,
  //         ID: item.id,
  //         items: [],
  //         tables: [],
  //       };
  //     }
  //     acc[key].items.push(item);
  //     if (item.Type === "TABLE") {
  //       acc[key].tables.push(item);
  //     }
  //     return acc;
  //   }, {}),
  // );
  // HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
  // const grouped = Object.values(
  //   (fetchAll || []).reduce((acc, item) => {
  //     const key = item.Title?.trim().toLowerCase() || "";

  //     if (!acc[key]) {
  //       acc[key] = {
  //         Title: item.Title,
  //         EN: item.EN,
  //         FA: item.FA,
  //         ID: item.id,
  //         items: [],
  //         tables: [],
  //       };
  //     }

  //     if (item.Type === "TABLE") {
  //       acc[key].tables.push(item);
  //     } else {
  //       acc[key].items.push(item);
  //     }

  //     return acc;
  //   }, {}),
  // );

  return (
    <AppProvider>
      <html lang="en">
        <body>
          {grouped.length === 0 ? (
            <Wrapper />
          ) : (
            <Bodi grouped={grouped} groupedTD={groupedTD} />
          )}
          {children}
          <Add />
        </body>
      </html>
    </AppProvider>
  );
}
